# 端口号
server:
    port: 8090
    tomcat:
        max-threads: 1000
# 数据库相关
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/application
    username: root
    password: 77545211
    #初始化大小
    initial-size: 5
    min-idle: 5
    max-active: 20
    #配置获取连接等待超时时间
    max-wait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    #配置一个连接在池中的最小生存时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #打开PSCache,并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters,去掉后监控界面sql将无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true


# 日志
logging:
  config: classpath:logback.xml

#mybatis-plus:
#    mapper-locations: classpath:/mapper/*Mapper.xml
#    global-config:
#        # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#        id-type: 0
#        # 驼峰下划线转换
#        db-column-underline: true
#    configuration:
#        map-underscore-to-camel-case: true
#        cache-enabled: false

swagger:
  project:
    version: 0.0.1-SNAPSHOT
    title: example-project
    description:


